create table if not exists auth_user (
    id bigint generated by default as identity primary key,
    user_id varchar(50) not null,
    user_name varchar(100) not null,
    password_hash varchar(200) not null,
    status varchar(20) not null
);
