create table if not exists member (
    id bigint generated by default as identity primary key,
    member_no varchar(50) not null,
    member_name varchar(100) not null,
    status varchar(20) not null
);

create table if not exists member_process (
    id bigint generated by default as identity primary key,
    process_id varchar(100) not null,
    process_type varchar(100) not null,
    process_name varchar(100) not null,
    business_key varchar(100) not null,
    trace_id varchar(100) not null,
    status varchar(30) not null,
    start_time timestamp,
    end_time timestamp,
    elapsed_ms bigint,
    error_code varchar(100),
    error_type varchar(50),
    error_message varchar(500)
);

create table if not exists member_process_step (
    id bigint generated by default as identity primary key,
    process_id varchar(100) not null,
    step_id varchar(100) not null,
    step_name varchar(100),
    service_name varchar(100) not null,
    status varchar(30) not null,
    start_time timestamp,
    end_time timestamp,
    elapsed_ms bigint,
    error_code varchar(100),
    error_type varchar(50),
    error_message varchar(500)
);

create table if not exists member_process_event (
    id bigint generated by default as identity primary key,
    process_id varchar(100) not null,
    step_id varchar(100),
    event_type varchar(100) not null,
    event_time timestamp,
    service_name varchar(100) not null,
    message varchar(500),
    status varchar(30)
);

create table if not exists trace_event (
    id bigint generated by default as identity primary key,
    trace_id varchar(100) not null,
    process_id varchar(100),
    business_key varchar(100),
    process_type varchar(100),
    step_id varchar(100),
    service_name varchar(100),
    event_type varchar(50) not null,
    http_method varchar(20),
    path varchar(500),
    status varchar(30),
    elapsed_ms bigint,
    error_code varchar(100),
    error_message varchar(1000),
    created_at timestamp
);

insert into member (member_no, member_name, status) values ('M001', '홍길동', 'ACTIVE');
insert into member (member_no, member_name, status) values ('M002', '김철수', 'INACTIVE');
