create table if not exists trace_event (
    id bigint generated by default as identity primary key,
    trace_id varchar(100) not null,
    process_id varchar(100),
    business_key varchar(100),
    process_type varchar(100),
    step_id varchar(100),
    service_name varchar(100),
    event_type varchar(50) not null,
    http_method varchar(20),
    path varchar(500),
    status varchar(30),
    elapsed_ms bigint,
    error_code varchar(100),
    error_message varchar(1000),
    created_at timestamp
);
