create table if not exists hr_employee (
    id bigint generated by default as identity primary key,
    employee_no varchar(50) not null,
    employee_name varchar(100) not null,
    status varchar(20) not null
);

insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10001', '홍길동', 'ACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10002', '김철수', 'INACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10003', '이영희', 'ACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10004', '박민수', 'ACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10005', '최지훈', 'INACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10006', '정수진', 'ACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10007', '한지민', 'ACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10008', '오세훈', 'INACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10009', '서연우', 'ACTIVE');
insert into hr_employee (employee_no, employee_name, status) values ('EMPLOYEE-10010', '조민재', 'ACTIVE');
